name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs:
  bucket:
    description: 'The name of the S3 bucket to deploy to.'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket.'
    required: true
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
runs:
  using: 'node16'
  #pre:
  main: 'main.js'
  #post: